import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-neutral-900 dark:bg-neutral-950 dark:text-neutral-100`}>
        <div className="min-h-dvh flex flex-col">
          <main className="flex-1 container py-4">{children}</main>
          <nav className="sticky bottom-0 border-t border-neutral-200 dark:border-neutral-800 bg-white/90 dark:bg-neutral-950/90 backdrop-blur bottom-safe-area">
            <ul className="grid grid-cols-4 text-sm">
              <li>
                <a href="/" className="block text-center p-3">Home</a>
              </li>
              <li>
                <a href="/lehrplan" className="block text-center p-3">Lehrplan</a>
              </li>
              <li>
                <a href="/forum" className="block text-center p-3">Forum</a>
              </li>
              <li>
                <a href="/profile" className="block text-center p-3">Profile</a>
              </li>
            </ul>
          </nav>
        </div>
      </body>
    </html>
  );
}
